version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
  - package-ecosystem: docker
    directory: /
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
  - package-ecosystem: github-actions
    directory: /
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
  - package-ecosystem: nuget
    directory: /
    schedule: 
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
